export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const PUT_SUCCESS = "PUT_SUCCESS";
export const PUT_FAILURE = "PUT_FAILURE";
export const GET_ALL_FAILURE = "GET_ALL_FAILURE";